version: "3.8"
services:
  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
  backend:
    build: ./backend
    ports:
      - '5555:5555'
    volumes:
      - ./backend:/app
      - /app/node_modules